/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer User
 */
public class PlanetZirboin extends javax.swing.JFrame {

    /**
     * Creates new form PlanetZirboin
     */
    public PlanetZirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVrobits = new javax.swing.JLabel();
        txtVrobits = new javax.swing.JTextField();
        btnExchange = new javax.swing.JButton();
        lblDrobzits = new javax.swing.JLabel();
        lblGazoontights = new javax.swing.JLabel();
        lblClickwicks = new javax.swing.JLabel();
        lblFrazoints = new javax.swing.JLabel();
        lblBlointoins = new javax.swing.JLabel();
        lblLeftVrobits = new javax.swing.JLabel();
        lblDrobDisp = new javax.swing.JLabel();
        lblFrazDisp = new javax.swing.JLabel();
        lblClickDisp = new javax.swing.JLabel();
        lblGazoonDisp = new javax.swing.JLabel();
        lblLeftVroDisp = new javax.swing.JLabel();
        lblBloinDisp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVrobits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVrobits.setText("Enter the number of  vrobits:");

        txtVrobits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnExchange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExchange.setText("Exchange");
        btnExchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExchangeActionPerformed(evt);
            }
        });

        lblDrobzits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDrobzits.setText("the number of  drobzits:");

        lblGazoontights.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblGazoontights.setText("the number of  gazoontights:");

        lblClickwicks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClickwicks.setText("the number of  clickwicks :");

        lblFrazoints.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFrazoints.setText("the number of  frazoints:");

        lblBlointoins.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBlointoins.setText("the number of  blointoints:");

        lblLeftVrobits.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLeftVrobits.setText("the number of  leftover vrobits:");

        lblDrobDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblFrazDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblClickDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblGazoonDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblLeftVroDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblBloinDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnExchange))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDrobzits, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDrobDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBlointoins, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblBloinDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFrazoints, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFrazDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblClickwicks, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblClickDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblGazoontights, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblGazoonDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblLeftVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLeftVroDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVrobits)
                    .addComponent(txtVrobits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnExchange)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrobzits)
                    .addComponent(lblDrobDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClickwicks)
                    .addComponent(lblClickDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGazoontights)
                    .addComponent(lblGazoonDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrazoints, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFrazDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBlointoins, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBloinDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeftVrobits, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLeftVroDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExchangeActionPerformed
        // TODO add your handling code here:
        
        int vroTotal = 0;
        int drobzits;
        int clickwicks;
        int gazoontights;
        int frazoints;
        int blointoints;
        int vroLeft;
        
        try
        {
            vroTotal = Integer.parseInt(txtVrobits.getText());
        }
        catch(Exception e)
        {
            txtVrobits.setText("");
            lblDrobDisp.setText("");
            lblClickDisp.setText("");
            lblGazoonDisp.setText("");
            lblFrazDisp.setText("");
            lblBloinDisp.setText("");
            lblLeftVroDisp.setText("");
            return;
        }
            
        int remainVro;
        drobzits = vroTotal / 100000;
        clickwicks = (vroTotal%100000)/ 50000;
        gazoontights = (vroTotal%50000) / 10000;
        frazoints = (vroTotal%10000) / 1000;
        blointoints = (vroTotal%1000) / 500;
        vroLeft = vroTotal %500;
        
        lblDrobDisp.setText(String.valueOf(drobzits));
        lblClickDisp.setText(String.valueOf(clickwicks));
        lblGazoonDisp.setText(String.valueOf(gazoontights));
        lblFrazDisp.setText(String.valueOf(frazoints));
        lblBloinDisp.setText(String.valueOf(blointoints));
        lblLeftVroDisp.setText(String.valueOf(vroLeft));
        
        
        
    }//GEN-LAST:event_btnExchangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanetZirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExchange;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBloinDisp;
    private javax.swing.JLabel lblBlointoins;
    private javax.swing.JLabel lblClickDisp;
    private javax.swing.JLabel lblClickwicks;
    private javax.swing.JLabel lblDrobDisp;
    private javax.swing.JLabel lblDrobzits;
    private javax.swing.JLabel lblFrazDisp;
    private javax.swing.JLabel lblFrazoints;
    private javax.swing.JLabel lblGazoonDisp;
    private javax.swing.JLabel lblGazoontights;
    private javax.swing.JLabel lblLeftVroDisp;
    private javax.swing.JLabel lblLeftVrobits;
    private javax.swing.JLabel lblVrobits;
    private javax.swing.JTextField txtVrobits;
    // End of variables declaration//GEN-END:variables
}
